"""Centralised EU7-LD (UN 168) limit definitions used across the stack."""

from __future__ import annotations

# Pre/Post zero & span drift limits (ppm)
CO2_ZERO_DRIFT_PPM_MAX = 2000.0
CO2_SPAN_DRIFT_PPM_MAX = 3914.0
CO_ZERO_DRIFT_PPM_MAX = 75.0
CO_SPAN_DRIFT_PPM_MAX = 943.4
NOX_ZERO_DRIFT_PPM_MAX = 3.0
NOX_SPAN_DRIFT_PPM_MAX = 144.3
PN_ZERO_HASH_CM3_MAX = 5000.0

# Span coverage thresholds (%)
SPAN_COVERAGE_MIN = 90.0
SPAN_TWO_X_BAND_MAX_PERCENT = 1.0
SPAN_EXCEED_MAX_COUNT = 0

# Vehicle preconditioning & soak
PRECONDITIONING_OPERATION_MIN_MINUTES = 10.0
SOAK_DURATION_HOURS_RANGE = (6.0, 72.0)
SOAK_TEMPERATURE_C_RANGE = (-7.0, 38.0)
COLD_START_EXTENDED_LOW_RANGE = (-7.0, 0.0)
COLD_START_EXTENDED_HIGH_RANGE = (35.0, 38.0)

# Cold-start window
COLD_START_AVG_SPEED_RANGE_KMH = (15.0, 40.0)
COLD_START_MAX_SPEED_KMH_MAX = 60.0
COLD_START_MOVE_WITHIN_SECONDS_MAX = 15.0
COLD_START_TOTAL_STOP_SECONDS_MAX = 90.0

# Trip composition & timing
TRIP_ORDER_SEQUENCE = ("urban", "rural", "expressway")
URBAN_DISTANCE_MIN_KM = 16.0
EXPRESSWAY_DISTANCE_MIN_KM = 16.0
URBAN_SHARE_PERCENT_RANGE = (45.0, 65.0)
EXPRESSWAY_SHARE_PERCENT_RANGE = (35.0, 55.0)
TRIP_DURATION_MINUTES_RANGE = (90.0, 120.0)
START_END_ELEVATION_DELTA_MAX_M = 100.0
CUMULATIVE_ELEVATION_TRIP_MAX_M_PER_100KM = 1200.0
CUMULATIVE_ELEVATION_URBAN_MAX_M_PER_100KM = 1200.0

# GPS validity
GPS_DISTANCE_DELTA_ABS_PERCENT_MAX = 4.0
GPS_MAX_GAP_SECONDS_MAX = 120.0
GPS_TOTAL_GAPS_SECONDS_MAX = 300.0

# Dynamics & MAW
ACCELERATION_EVENTS_MIN = 100
VA_POS95_URBAN_MAX = 18.741
VA_POS95_EXPRESSWAY_MAX = 24.708
RPA_URBAN_MIN = 0.125
RPA_EXPRESSWAY_MIN = 0.052

# CO₂ characteristic windows
MAW_LOW_SPEED_VALID_PERCENT_MIN = 50.0
MAW_HIGH_SPEED_VALID_PERCENT_MIN = 50.0

# Final pollutant limits
FINAL_NOX_MG_KM_LIMIT = 60.0
FINAL_PN_HASH_KM_LIMIT = 6.0e11
FINAL_CO_MG_KM_LIMIT = 1000.0

# Leak checks & device errors
GAS_PEMS_LEAK_RATE_PERCENT_MAX = 0.5
PN_DILUTE_PRESSURE_RISE_MBAR_MAX = 30.0
PN_SAMPLE_PRESSURE_RISE_MBAR_MAX = 30.0
DEVICE_ERROR_COUNT_MAX = 0

__all__ = [
    "ACCELERATION_EVENTS_MIN",
    "COLD_START_AVG_SPEED_RANGE_KMH",
    "COLD_START_EXTENDED_HIGH_RANGE",
    "COLD_START_EXTENDED_LOW_RANGE",
    "COLD_START_MAX_SPEED_KMH_MAX",
    "COLD_START_MOVE_WITHIN_SECONDS_MAX",
    "COLD_START_TOTAL_STOP_SECONDS_MAX",
    "CO2_SPAN_DRIFT_PPM_MAX",
    "CO2_ZERO_DRIFT_PPM_MAX",
    "CO_SPAN_DRIFT_PPM_MAX",
    "CO_ZERO_DRIFT_PPM_MAX",
    "CUMULATIVE_ELEVATION_TRIP_MAX_M_PER_100KM",
    "CUMULATIVE_ELEVATION_URBAN_MAX_M_PER_100KM",
    "DEVICE_ERROR_COUNT_MAX",
    "EXPRESSWAY_DISTANCE_MIN_KM",
    "EXPRESSWAY_SHARE_PERCENT_RANGE",
    "FINAL_CO_MG_KM_LIMIT",
    "FINAL_NOX_MG_KM_LIMIT",
    "FINAL_PN_HASH_KM_LIMIT",
    "GAS_PEMS_LEAK_RATE_PERCENT_MAX",
    "GPS_DISTANCE_DELTA_ABS_PERCENT_MAX",
    "GPS_MAX_GAP_SECONDS_MAX",
    "GPS_TOTAL_GAPS_SECONDS_MAX",
    "MAW_HIGH_SPEED_VALID_PERCENT_MIN",
    "MAW_LOW_SPEED_VALID_PERCENT_MIN",
    "NOX_SPAN_DRIFT_PPM_MAX",
    "NOX_ZERO_DRIFT_PPM_MAX",
    "PN_DILUTE_PRESSURE_RISE_MBAR_MAX",
    "PN_SAMPLE_PRESSURE_RISE_MBAR_MAX",
    "PN_ZERO_HASH_CM3_MAX",
    "PRECONDITIONING_OPERATION_MIN_MINUTES",
    "RPA_EXPRESSWAY_MIN",
    "RPA_URBAN_MIN",
    "SOAK_DURATION_HOURS_RANGE",
    "SOAK_TEMPERATURE_C_RANGE",
    "SPAN_COVERAGE_MIN",
    "SPAN_EXCEED_MAX_COUNT",
    "SPAN_TWO_X_BAND_MAX_PERCENT",
    "START_END_ELEVATION_DELTA_MAX_M",
    "TRIP_DURATION_MINUTES_RANGE",
    "TRIP_ORDER_SEQUENCE",
    "URBAN_DISTANCE_MIN_KM",
    "URBAN_SHARE_PERCENT_RANGE",
    "VA_POS95_EXPRESSWAY_MAX",
    "VA_POS95_URBAN_MAX",
]
