"""Centralised EU7-LD (UN R168 & Euro 7) limit definitions used across the stack."""

from __future__ import annotations

# Final limits for LD RDE (EU7) – Regulation (EU) 2025/1706 Annex III Table 1.
NOX_RDE_FINAL_MG_PER_KM: float = 60.0  # EU_7_202501706_EN_TXT.pdf Annex III Table 1
PN10_RDE_FINAL_PER_KM: float = 6.0e11  # EU_7_202501706_EN_TXT.pdf Annex III Table 1
CO_WLTP_LIMIT_MG_PER_KM: float = 1000.0  # EU_7_202501706_EN_TXT.pdf Annex III Table 1

# Gas PEMS absolute drift (ppm) – UN R168 Annex 7 Appendix 2 Table 4.
CO2_ZERO_PPM_MAX: float = 2000.0  # un168.pdf Annex 7 App.2 Table 4
CO2_SPAN_PPM_MAX: float = 3914.0  # un168.pdf Annex 7 App.2 Table 4
CO_ZERO_PPM_MAX: float = 75.0  # un168.pdf Annex 7 App.2 Table 4
CO_SPAN_PPM_MAX: float = 943.4  # un168.pdf Annex 7 App.2 Table 4
NOX_ZERO_PPM_MAX: float = 3.0  # un168.pdf Annex 7 App.2 Table 4
NOX_SPAN_PPM_MAX: float = 144.3  # un168.pdf Annex 7 App.2 Table 4

# PN zeros (#/cm³) – UN R168 Annex 7 Appendix 2 §6.5.2.
PN_ZERO_PRE_MAX_PER_CM3: float = 5000.0  # un168.pdf Annex 7 App.2 §6.5.2
PN_ZERO_POST_MAX_PER_CM3: float = 5000.0  # un168.pdf Annex 7 App.2 §6.5.2

# GPS validity – UN R168 Annex 7 Appendix 2 §4.6.3.
GPS_SINGLE_GAP_S_MAX: float = 120.0  # un168.pdf Annex 7 App.2 §4.6.3
GPS_TOTAL_GAPS_S_MAX: float = 300.0  # un168.pdf Annex 7 App.2 §4.6.3
GPS_ECU_DISTANCE_DIFF_PCT_MAX: float = 4.0  # un168.pdf Annex 7 App.2 §4.6.3

# Trip composition/duration/elevation – UN R168 Annex 7 Appendix 2 §§6.2–6.4.
# Canonical names (used internally going forward)
START_END_ELEV_ABS_M_MAX: float = 100.0  # un168.pdf Annex 7 App.2 §6.4.1
CUM_POS_ELEV_TRIP_M_PER_100KM_MAX: float = 1200.0  # un168.pdf Annex 7 App.2 §6.4.3
CUM_POS_ELEV_URBAN_M_PER_100KM_MAX: float = 1200.0  # un168.pdf Annex 7 App.2 §6.4.3
TRIP_DURATION_MIN_MIN: float = 90.0  # un168.pdf Annex 7 App.2 §6.3.1
TRIP_DURATION_MAX_MIN: float = 120.0  # un168.pdf Annex 7 App.2 §6.3.1
URBAN_MIN_DISTANCE_KM: float = 16.0  # un168.pdf Annex 7 App.2 §6.2.1
MOTORWAY_MIN_DISTANCE_KM: float = 16.0  # un168.pdf Annex 7 App.2 §6.2.3

# Backward-compat aliases (keep until all imports are migrated)
CUMULATIVE_ELEVATION_TRIP_MAX_M_PER_100KM = CUM_POS_ELEV_TRIP_M_PER_100KM_MAX
CUMULATIVE_ELEVATION_URBAN_MAX_M_PER_100KM = CUM_POS_ELEV_URBAN_M_PER_100KM_MAX
START_END_ELEVATION_ABS_M_MAX = START_END_ELEV_ABS_M_MAX

# Cold-start window – UN R168 Annex 7 Appendix 2 §6.6.
COLD_START_AVG_SPEED_MIN_KMH: float = 15.0  # un168.pdf Annex 7 App.2 §6.6.4
COLD_START_AVG_SPEED_MAX_KMH: float = 40.0  # un168.pdf Annex 7 App.2 §6.6.4
COLD_START_MAX_SPEED_KMH: float = 60.0  # un168.pdf Annex 7 App.2 §6.6.4
COLD_START_MOVE_TIME_MAX_S: float = 15.0  # un168.pdf Annex 7 App.2 §6.6.2
COLD_START_TOTAL_STOP_MAX_S: float = 90.0  # un168.pdf Annex 7 App.2 §6.6.4
COLD_START_EXTENDED_TEMP_LOW_C: tuple[float, float] = (-7.0, 0.0)  # un168.pdf Annex 7 App.2 §6.6.6
COLD_START_EXTENDED_TEMP_HIGH_C: tuple[float, float] = (35.0, 38.0)  # un168.pdf Annex 7 App.2 §6.6.6
COLD_START_EXTENDED_FACTOR: float = 1.6  # un168.pdf Annex 7 App.2 §6.6.6

# Span coverage thresholds (%) – UN R168 Annex 7 Appendix 2 §5.5.
SPAN_COVERAGE_MIN_PCT: float = 90.0  # un168.pdf Annex 7 App.2 §5.5
SPAN_TWO_X_BAND_MAX_PCT: float = 1.0  # un168.pdf Annex 7 App.2 §5.5
SPAN_ABOVE_TWO_X_MAX_COUNT: int = 0  # un168.pdf Annex 7 App.2 §5.5

# Dynamics thresholds per Euro 6e amendment – Annex IIIA Appendix 7 (light-duty).
ACCEL_EVENTS_MIN: int = 100  # Com_Regulation_EU_2023_443_am_2017-1151_Euro6e.pdf Annex IIIA App.7 §3.3
VA_POS95_LOW_SPEED_SLOPE: float = 0.136  # Com_Regulation_EU_2023_443_am_2017-1151_Euro6e.pdf Annex IIIA App.7 Table 2
VA_POS95_LOW_SPEED_OFFSET: float = 14.44  # Com_Regulation_EU_2023_443_am_2017-1151_Euro6e.pdf Annex IIIA App.7 Table 2
VA_POS95_HIGH_SPEED_SLOPE: float = 0.0742  # Com_Regulation_EU_2023_443_am_2017-1151_Euro6e.pdf Annex IIIA App.7 Table 2
VA_POS95_HIGH_SPEED_OFFSET: float = 18.966  # Com_Regulation_EU_2023_443_am_2017-1151_Euro6e.pdf Annex IIIA App.7 Table 2
VA_POS95_ALT_HIGH_SPEED_SLOPE: float = -0.097  # Com_Regulation_EU_2023_443_am_2017-1151_Euro6e.pdf Annex IIIA App.7 Table 2
VA_POS95_ALT_HIGH_SPEED_OFFSET: float = 31.365  # Com_Regulation_EU_2023_443_am_2017-1151_Euro6e.pdf Annex IIIA App.7 Table 2
VA_POS95_BREAK_KMH: float = 74.6  # Com_Regulation_EU_2023_443_am_2017-1151_Euro6e.pdf Annex IIIA App.7 Table 2
RPA_BREAK_KMH: float = 94.05  # Com_Regulation_EU_2023_443_am_2017-1151_Euro6e.pdf Annex IIIA App.7 §3.4
RPA_LOW_SPEED_SLOPE: float = -0.0016  # Com_Regulation_EU_2023_443_am_2017-1151_Euro6e.pdf Annex IIIA App.7 §3.4
RPA_LOW_SPEED_OFFSET: float = 0.1755  # Com_Regulation_EU_2023_443_am_2017-1151_Euro6e.pdf Annex IIIA App.7 §3.4
RPA_HIGH_SPEED_MIN: float = 0.025  # Com_Regulation_EU_2023_443_am_2017-1151_Euro6e.pdf Annex IIIA App.7 §3.4

__all__ = [
    # canonical
    "START_END_ELEV_ABS_M_MAX",
    "CUM_POS_ELEV_TRIP_M_PER_100KM_MAX",
    "CUM_POS_ELEV_URBAN_M_PER_100KM_MAX",
    "TRIP_DURATION_MIN_MIN",
    "TRIP_DURATION_MAX_MIN",
    "URBAN_MIN_DISTANCE_KM",
    "MOTORWAY_MIN_DISTANCE_KM",
    # aliases (compat)
    "CUMULATIVE_ELEVATION_TRIP_MAX_M_PER_100KM",
    "CUMULATIVE_ELEVATION_URBAN_MAX_M_PER_100KM",
    "START_END_ELEVATION_ABS_M_MAX",
    # existing exports
    "ACCEL_EVENTS_MIN",
    "COLD_START_AVG_SPEED_MAX_KMH",
    "COLD_START_AVG_SPEED_MIN_KMH",
    "COLD_START_EXTENDED_FACTOR",
    "COLD_START_EXTENDED_TEMP_HIGH_C",
    "COLD_START_EXTENDED_TEMP_LOW_C",
    "COLD_START_MAX_SPEED_KMH",
    "COLD_START_MOVE_TIME_MAX_S",
    "COLD_START_TOTAL_STOP_MAX_S",
    "CO2_SPAN_PPM_MAX",
    "CO2_ZERO_PPM_MAX",
    "CO_SPAN_PPM_MAX",
    "CO_WLTP_LIMIT_MG_PER_KM",
    "CO_ZERO_PPM_MAX",
    "GPS_ECU_DISTANCE_DIFF_PCT_MAX",
    "GPS_SINGLE_GAP_S_MAX",
    "GPS_TOTAL_GAPS_S_MAX",
    "NOX_RDE_FINAL_MG_PER_KM",
    "NOX_SPAN_PPM_MAX",
    "NOX_ZERO_PPM_MAX",
    "PN10_RDE_FINAL_PER_KM",
    "PN_ZERO_POST_MAX_PER_CM3",
    "PN_ZERO_PRE_MAX_PER_CM3",
    "RPA_BREAK_KMH",
    "RPA_HIGH_SPEED_MIN",
    "RPA_LOW_SPEED_OFFSET",
    "RPA_LOW_SPEED_SLOPE",
    "SPAN_ABOVE_TWO_X_MAX_COUNT",
    "SPAN_COVERAGE_MIN_PCT",
    "SPAN_TWO_X_BAND_MAX_PCT",
    "VA_POS95_ALT_HIGH_SPEED_OFFSET",
    "VA_POS95_ALT_HIGH_SPEED_SLOPE",
    "VA_POS95_BREAK_KMH",
    "VA_POS95_HIGH_SPEED_OFFSET",
    "VA_POS95_HIGH_SPEED_SLOPE",
    "VA_POS95_LOW_SPEED_OFFSET",
    "VA_POS95_LOW_SPEED_SLOPE",
]

# Backwards compatible aliases retained for report utilities expecting legacy names.
FINAL_NOX_MG_KM_LIMIT = NOX_RDE_FINAL_MG_PER_KM
FINAL_PN_HASH_KM_LIMIT = PN10_RDE_FINAL_PER_KM
FINAL_CO_MG_KM_LIMIT = CO_WLTP_LIMIT_MG_PER_KM
ACCELERATION_EVENTS_MIN = ACCEL_EVENTS_MIN
COLD_START_AVG_SPEED_RANGE_KMH = (COLD_START_AVG_SPEED_MIN_KMH, COLD_START_AVG_SPEED_MAX_KMH)
COLD_START_EXTENDED_HIGH_RANGE = COLD_START_EXTENDED_TEMP_HIGH_C
COLD_START_EXTENDED_LOW_RANGE = COLD_START_EXTENDED_TEMP_LOW_C
COLD_START_MAX_SPEED_KMH_MAX = COLD_START_MAX_SPEED_KMH
COLD_START_MOVE_WITHIN_SECONDS_MAX = COLD_START_MOVE_TIME_MAX_S
COLD_START_TOTAL_STOP_SECONDS_MAX = COLD_START_TOTAL_STOP_MAX_S
CO2_SPAN_DRIFT_PPM_MAX = CO2_SPAN_PPM_MAX
CO2_ZERO_DRIFT_PPM_MAX = CO2_ZERO_PPM_MAX
CO_SPAN_DRIFT_PPM_MAX = CO_SPAN_PPM_MAX
CO_ZERO_DRIFT_PPM_MAX = CO_ZERO_PPM_MAX
GPS_DISTANCE_DELTA_ABS_PERCENT_MAX = GPS_ECU_DISTANCE_DIFF_PCT_MAX
GPS_MAX_GAP_SECONDS_MAX = GPS_SINGLE_GAP_S_MAX
GPS_TOTAL_GAPS_SECONDS_MAX = GPS_TOTAL_GAPS_S_MAX
SPAN_COVERAGE_MIN = SPAN_COVERAGE_MIN_PCT
SPAN_TWO_X_BAND_MAX_PERCENT = SPAN_TWO_X_BAND_MAX_PCT
SPAN_EXCEED_MAX_COUNT = SPAN_ABOVE_TWO_X_MAX_COUNT
TRIP_DURATION_MINUTES_RANGE = (TRIP_DURATION_MIN_MIN, TRIP_DURATION_MAX_MIN)
START_END_ELEVATION_DELTA_MAX_M = START_END_ELEV_ABS_M_MAX
EXPRESSWAY_DISTANCE_MIN_KM = MOTORWAY_MIN_DISTANCE_KM
URBAN_SHARE_PERCENT_RANGE = (45.0, 65.0)
EXPRESSWAY_SHARE_PERCENT_RANGE = (35.0, 55.0)
TRIP_ORDER_SEQUENCE = ("urban", "rural", "motorway")
PN_ZERO_HASH_CM3_MAX = PN_ZERO_PRE_MAX_PER_CM3
RPA_EXPRESSWAY_MIN = RPA_HIGH_SPEED_MIN
RPA_URBAN_MIN = RPA_LOW_SPEED_OFFSET
VA_POS95_EXPRESSWAY_MAX = VA_POS95_HIGH_SPEED_OFFSET
VA_POS95_URBAN_MAX = VA_POS95_LOW_SPEED_OFFSET
MAW_LOW_SPEED_VALID_PERCENT_MIN = 50.0
MAW_HIGH_SPEED_VALID_PERCENT_MIN = 50.0
PRECONDITIONING_OPERATION_MIN_MINUTES = 10.0
SOAK_DURATION_HOURS_RANGE = (6.0, 72.0)
SOAK_TEMPERATURE_C_RANGE = (-7.0, 38.0)
DEVICE_ERROR_COUNT_MAX = 0
GAS_PEMS_LEAK_RATE_PERCENT_MAX = 0.5
PN_DILUTE_PRESSURE_RISE_MBAR_MAX = 30.0
PN_SAMPLE_PRESSURE_RISE_MBAR_MAX = 30.0

__all__ += [
    "ACCELERATION_EVENTS_MIN",
    "COLD_START_AVG_SPEED_RANGE_KMH",
    "COLD_START_EXTENDED_HIGH_RANGE",
    "COLD_START_EXTENDED_LOW_RANGE",
    "COLD_START_MAX_SPEED_KMH_MAX",
    "COLD_START_MOVE_WITHIN_SECONDS_MAX",
    "COLD_START_TOTAL_STOP_SECONDS_MAX",
    "CO2_SPAN_DRIFT_PPM_MAX",
    "CO2_ZERO_DRIFT_PPM_MAX",
    "CO_SPAN_DRIFT_PPM_MAX",
    "CO_ZERO_DRIFT_PPM_MAX",
    "DEVICE_ERROR_COUNT_MAX",
    "EXPRESSWAY_DISTANCE_MIN_KM",
    "EXPRESSWAY_SHARE_PERCENT_RANGE",
    "GAS_PEMS_LEAK_RATE_PERCENT_MAX",
    "GPS_DISTANCE_DELTA_ABS_PERCENT_MAX",
    "GPS_MAX_GAP_SECONDS_MAX",
    "GPS_TOTAL_GAPS_SECONDS_MAX",
    "MAW_HIGH_SPEED_VALID_PERCENT_MIN",
    "MAW_LOW_SPEED_VALID_PERCENT_MIN",
    "PN_DILUTE_PRESSURE_RISE_MBAR_MAX",
    "PN_SAMPLE_PRESSURE_RISE_MBAR_MAX",
    "PN_ZERO_HASH_CM3_MAX",
    "PRECONDITIONING_OPERATION_MIN_MINUTES",
    "RPA_EXPRESSWAY_MIN",
    "RPA_URBAN_MIN",
    "SOAK_DURATION_HOURS_RANGE",
    "SOAK_TEMPERATURE_C_RANGE",
    "SPAN_COVERAGE_MIN",
    "SPAN_EXCEED_MAX_COUNT",
    "SPAN_TWO_X_BAND_MAX_PERCENT",
    "START_END_ELEVATION_DELTA_MAX_M",
    "TRIP_DURATION_MINUTES_RANGE",
    "TRIP_ORDER_SEQUENCE",
    "URBAN_SHARE_PERCENT_RANGE",
    "VA_POS95_EXPRESSWAY_MAX",
    "VA_POS95_URBAN_MAX",
]
